### ISSUE TITLE
Road Runner up/down inputs

### ISSUE THREAD

**Issue by hayesmaker** [d18c7db/atari_system1_fpga#9] opened 2023-12-09 18:28 UTC
Up and Down directions aren;'t working and can't be mapped in this core.

Mister v231018
OS v231108

A.Atarisys1 v231025

I tried Road Runner (rev 1, rev 1p and rev2).  Define roadrunn1 buttons menu in Mister.

**Comment by d18c7db** [comment] 2023-12-11 11:14
This is a duplicate of issue opened here https://github.com/MiSTer-devel/Arcade-Atari-system1_MiSTer/issues/1

Are you and fiermanb using the same controller in the same way (analog joytick for left/right and digital buttons for up/down)?
I'm very curious how it's possible to end up in this situation with mixed digital/analog controls.
Can you please describe your exact setup for your controllers including model numbers if possible?

The Road Runner core does not currently support digital inputs (d-pad) but if you use the analog stick of your joystick it should work fine for all directions. Digital control will be added in a future update.

The real Road Runner arcade was not designed to take digital (on/off switches) as inputs as can be seen by the fact they they connect analog potentiometers to the directional inputs, see Technical Manual TM-285 page 3-5 figure 3-3 potentiometer R6 and R7 are the X and Y controls.

I can't speak for the original designers of the arcade, if they intended for fine directional control input. If this is the case then a simple digital on-off button cannot achieve that electrically, you can't press an on-off button 3/4 of the way or 1/2 of the way to give you fine control, the button is electrically either on or off. An analog joystick can be however move to any position in between idle position and fully pushed in any direction giving you the full range of values in between via the potentiometer.

In other simple words you can NOT emulate an analog control with a simple on-off button. Your issue report will be treated as a feature request.

**Closed as completed** 2023-12-13 23:01 UTC

**Comment by hayesmaker** [comment] 2023-12-19 09:18
I wasn't using dual analog / digital inputs... I was using a usb arcade stick with x-input compatibility. Works fine with every mister core.   Anyway, I did an  update_all, and the issue's been fixed.
